### ISSUE TITLE
Class turtle_lsystem typo

### ISSUE THREAD

**Issue by nomssi** [FreHu/abap-turtle-graphics#17]
While converting the package to local classes (it is now used in ABAP Scheme),  I found this typo (**forwrad**) that probably has no functional impact:

```
    CONSTANTS:
      BEGIN OF instruction_kind,
...
        forward    type lsystem_instruction_kind value `forwrad`,
```
Just to let you know.

**Comment by FreHu** [comment]
Fixed nonetheless. Thanks.
