### ISSUE TITLE
class zcl_turtle_lsystem syntax error

### ISSUE THREAD

**Issue by nomssi** [FreHu/abap-turtle-graphics#9]
class zcl_turtle_lsystem , type lsystem_instruction,
        symbol type c1,  <== TYPE "C1" is unknown in my systrem

**Comment by FreHu** [comment]
Interesting, I thought this was a buitin type. What version are you using?

**Comment by FreHu** [comment]
Actually nevermind - you can do `symbol(1) type c` or `symbol type c length 1`. `c1` is just some random data element on my system.

Resolved in https://github.com/FreHu/abap-turtle-graphics/commit/223472ab7d2544a9be2a44f1a77862cb0087e4d4
